device: 2

# # Dataset settings
feat_dim: 4814
batch_size: 1024
num_sample: [20, 10, 5]

# # Training settings
epochs: 20
optim: adam
init_lr: 0.001
weight_decay: 0.0
use_schedule: true
step_size: 50
gamma: 0.5

lr_eval: 0.005
wd_eval: 0.0001
epochs_eval: 2000

# # Pretraining settings
mask_ratio: 0.25
replace_ratio: 0.0

masked_atom_loss: 1.0
masked_pe_loss: 0.001
atom_recon_type: sce
alpha_l: 3.0
noise_val: 0.01

# # Encoder & Decoder setting
enc_gnn_layer: 3
embed_dim: 1024
heads: 8
gnn_dropout: 0.0
gnn_edge_dropout: 0.0
gnn_activation: elu
task_head_activation: gelu

# # Positional Encoding (PE) settings
max_freqs: 200
pos_activation: gelu