device: 0

# # Dataset settings
num_atom_type: 119
batch_size: 32
num_workers: 0
pooling: mean

# # Training settings
epochs: 20
optim: adam
init_lr: 0.001
weight_decay: 0.0
schedule_opt: none

# # Pretraining settings
mask_ratio: 0.5
masked_atom_loss: 1.0
masked_pe_loss: 0.01
atom_recon_type: sce
alpha_l: 2.0
noise_val: 0.001

# # Encoder & Decoder setting
enc_gnn_layer: 2
embed_dim: 300
gnn_dropout: 0.6
gnn_edge_dropout: 0.6
gnn_activation: relu
task_head_activation: gelu

# # Positional Encoding (PE) settings
max_freqs: 30
lap_norm: sym
eigvec_norm: L2
pos_activation: gelu